# Task 44 – Pandas DataFrame
**Reference:** https://www.w3schools.com/python/pandas_dataframes.asp

In [1]:
import pandas as pd
data = {'calories': [420, 380, 390], 'duration': [50, 40, 45]}
df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [2]:
df2 = pd.DataFrame(data, index=['day1', 'day2', 'day3'])
df2

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [3]:
print('loc day2:\n', df2.loc['day2'])
print('iloc 0:\n', df2.iloc[0])

loc day2:
 calories    380
duration     40
Name: day2, dtype: int64
iloc 0:
 calories    420
duration     50
Name: day1, dtype: int64

In [4]:
df2['burned'] = [300, 250, 280]
df2

      calories  duration  burned
day1       420        50     300
day2       380        40     250
day3       390        45     280