# Task 47 – Pandas: Data Cleaning
**Reference:** https://www.w3schools.com/python/pandas_cleaning.asp

In [7]:
import pandas as pd, numpy as np
data = {'Name':['Ali','Sara',None,'Fatima','Usman'],'Age':[25,None,22,28,35],'Score':[88.5,92.0,78.3,None,70.4]}
df = pd.DataFrame(data)
df

     Name   Age  Score
0     Ali  25.0   88.5
1    Sara   NaN   92.0
2     NaN  22.0   78.3
3  Fatima  28.0    NaN
4   Usman  35.0   70.4

In [8]:
df.isnull().sum()

Name     1
Age      1
Score    1
dtype: int64

In [9]:
df.dropna()

    Name   Age  Score
0    Ali  25.0   88.5
4  Usman  35.0   70.4

In [10]:
# Create a copy
df2 = df.copy()

# Fill missing values using direct assignment (The Best Practice)
df2['Age'] = df2['Age'].fillna(df2['Age'].mean())
df2['Score'] = df2['Score'].fillna(df2['Score'].median())
df2['Name'] = df2['Name'].fillna('Unknown')

# Display the result
df2

      Name   Age  Score
0      Ali  25.0   88.5
1     Sara  27.5   92.0
2  Unknown  22.0   78.3
3   Fatima  28.0   83.4
4    Usman  35.0   70.4

In [11]:
df3 = pd.DataFrame({'A':[1,2,2,3],'B':[4,5,5,6]})
df3.drop_duplicates()

   A  B
0  1  4
1  2  5
3  3  6